//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Global", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Број на откажани клиенти.
        /// </summary>
        internal static string CANCELED_CUSTOMERS {
            get {
                return ResourceManager.GetString("CANCELED_CUSTOMERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прв шалтер.
        /// </summary>
        internal static string FIRST {
            get {
                return ResourceManager.GetString("FIRST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Физичко лице.
        /// </summary>
        internal static string FIZICKO_LICE {
            get {
                return ResourceManager.GetString("FIZICKO_LICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Послужен.
        /// </summary>
        internal static string POSLUZEN {
            get {
                return ResourceManager.GetString("POSLUZEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Правно лице.
        /// </summary>
        internal static string PRAVNO_LICE {
            get {
                return ResourceManager.GetString("PRAVNO_LICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Извештаи.
        /// </summary>
        internal static string REPORTS {
            get {
                return ResourceManager.GetString("REPORTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Втор шалтер.
        /// </summary>
        internal static string SECOND {
            get {
                return ResourceManager.GetString("SECOND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Број на услужени клиенти.
        /// </summary>
        internal static string SERVED_CUSTOMERS {
            get {
                return ResourceManager.GetString("SERVED_CUSTOMERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Број на услужени клиенти од друг шалтер.
        /// </summary>
        internal static string SERVED_CUSTOMERS_ANOTHER {
            get {
                return ResourceManager.GetString("SERVED_CUSTOMERS_ANOTHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Следен.
        /// </summary>
        internal static string SLEDEN {
            get {
                return ResourceManager.GetString("SLEDEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус.
        /// </summary>
        internal static string STATUS {
            get {
                return ResourceManager.GetString("STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заминал.
        /// </summary>
        internal static string ZAMINAL {
            get {
                return ResourceManager.GetString("ZAMINAL", resourceCulture);
            }
        }
    }
}
